## config

## server
server:
  port: 8604
  servlet:
    context-path: /cloud-alibaba-consumer-feign

## spring
spring:
  application:
    name: cloud-alibaba-server-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.140.10:8688

## endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"

## feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


