## config

## server
server:
  port: 8600

## spring
spring:
  application:
    name: cloud-alibaba-server-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.140.10:8688

## endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"


