## config

## server
server:
  port: 8612

## spring
spring:
  application:
    name: cloud-alibaba-gateway-filter
  ## datasource
  datasource:
    url: "jdbc:mysql://172.16.140.10:3306/demo?useUnicode=true&characterEncoding=utf8\
      &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
      &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true\
      &nullCatalogMeansCurrent=true"
    username: root
    password: "Qwert12345!"
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  ## cloud
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.140.10:8688
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      ## cors
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#      ## routes
#      routes:
#        - id: default_demo_route
#          uri: http://127.0.0.1:9000
#          predicates:
#            - Path=/api/**



## endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"

## feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

## log
#logging:
#  level:
#    org.springframework.cloud.gateway: debug

