## environment-dev

## tomcat server
server:
  port: 8848

spring:
  ## datasource
  datasource:
    user:
      url: "jdbc:mysql://172.16.140.10:3306/demo?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true\
          &useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useSSL=true&allowMultiQueries=true&autoReconnect=true"
      username: root
      password: "Qwert12345!"
    receiveAddress:
      url: "jdbc:mysql://172.16.140.10:3306/demo1?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true\
                &useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useSSL=true&allowMultiQueries=true&autoReconnect=true"
      username: root
      password: "Qwert12345!"


