// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ljq/demo/springboot/mybatisplus/model/protobuf/Tree.proto

package com.ljq.demo.springboot.mybatisplus.model.entity;

public final class TreePb {
  private TreePb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TreeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tree)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 树木品种
     * </pre>
     *
     * <code>string treeType = 2;</code>
     * @return The treeType.
     */
    java.lang.String getTreeType();
    /**
     * <pre>
     * 树木品种
     * </pre>
     *
     * <code>string treeType = 2;</code>
     * @return The bytes for treeType.
     */
    com.google.protobuf.ByteString
        getTreeTypeBytes();

    /**
     * <pre>
     * 植树时间
     * </pre>
     *
     * <code>uint32 plantDate = 3;</code>
     * @return The plantDate.
     */
    int getPlantDate();

    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     * @return Whether the student field is set.
     */
    boolean hasStudent();
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     * @return The student.
     */
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student getStudent();
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     */
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder getStudentOrBuilder();
  }
  /**
   * <pre>
   * 学生植树
   * </pre>
   *
   * Protobuf type {@code Tree}
   */
  public static final class Tree extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tree)
      TreeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tree.newBuilder() to construct.
    private Tree(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tree() {
      treeType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tree();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.class, com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.Builder.class);
    }

    public static final int TREETYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object treeType_;
    /**
     * <pre>
     * 树木品种
     * </pre>
     *
     * <code>string treeType = 2;</code>
     * @return The treeType.
     */
    @java.lang.Override
    public java.lang.String getTreeType() {
      java.lang.Object ref = treeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        treeType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 树木品种
     * </pre>
     *
     * <code>string treeType = 2;</code>
     * @return The bytes for treeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTreeTypeBytes() {
      java.lang.Object ref = treeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        treeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLANTDATE_FIELD_NUMBER = 3;
    private int plantDate_;
    /**
     * <pre>
     * 植树时间
     * </pre>
     *
     * <code>uint32 plantDate = 3;</code>
     * @return The plantDate.
     */
    @java.lang.Override
    public int getPlantDate() {
      return plantDate_;
    }

    public static final int STUDENT_FIELD_NUMBER = 4;
    private com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student student_;
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     * @return Whether the student field is set.
     */
    @java.lang.Override
    public boolean hasStudent() {
      return student_ != null;
    }
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     * @return The student.
     */
    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student getStudent() {
      return student_ == null ? com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.getDefaultInstance() : student_;
    }
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     */
    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder getStudentOrBuilder() {
      return getStudent();
    }

    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 学生植树
     * </pre>
     *
     * Protobuf type {@code Tree}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tree)
        com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.TreeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.class, com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.Builder.class);
      }

      // Construct using com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        treeType_ = "";

        plantDate_ = 0;

        if (studentBuilder_ == null) {
          student_ = null;
        } else {
          student_ = null;
          studentBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_descriptor;
      }

      @java.lang.Override
      public com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree getDefaultInstanceForType() {
        return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.getDefaultInstance();
      }

      @java.lang.Override
      public com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree build() {
        com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree buildPartial() {
        com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree result = new com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree(this);
        result.treeType_ = treeType_;
        result.plantDate_ = plantDate_;
        if (studentBuilder_ == null) {
          result.student_ = student_;
        } else {
          result.student_ = studentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      private java.lang.Object treeType_ = "";
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string treeType = 2;</code>
       * @return The treeType.
       */
      public java.lang.String getTreeType() {
        java.lang.Object ref = treeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          treeType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string treeType = 2;</code>
       * @return The bytes for treeType.
       */
      public com.google.protobuf.ByteString
          getTreeTypeBytes() {
        java.lang.Object ref = treeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          treeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string treeType = 2;</code>
       * @param value The treeType to set.
       * @return This builder for chaining.
       */
      public Builder setTreeType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        treeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string treeType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTreeType() {
        
        treeType_ = getDefaultInstance().getTreeType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string treeType = 2;</code>
       * @param value The bytes for treeType to set.
       * @return This builder for chaining.
       */
      public Builder setTreeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        treeType_ = value;
        onChanged();
        return this;
      }

      private int plantDate_ ;
      /**
       * <pre>
       * 植树时间
       * </pre>
       *
       * <code>uint32 plantDate = 3;</code>
       * @return The plantDate.
       */
      @java.lang.Override
      public int getPlantDate() {
        return plantDate_;
      }
      /**
       * <pre>
       * 植树时间
       * </pre>
       *
       * <code>uint32 plantDate = 3;</code>
       * @param value The plantDate to set.
       * @return This builder for chaining.
       */
      public Builder setPlantDate(int value) {
        
        plantDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 植树时间
       * </pre>
       *
       * <code>uint32 plantDate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlantDate() {
        
        plantDate_ = 0;
        onChanged();
        return this;
      }

      private com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student student_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder> studentBuilder_;
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       * @return Whether the student field is set.
       */
      public boolean hasStudent() {
        return studentBuilder_ != null || student_ != null;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       * @return The student.
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student getStudent() {
        if (studentBuilder_ == null) {
          return student_ == null ? com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.getDefaultInstance() : student_;
        } else {
          return studentBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public Builder setStudent(com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          student_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public Builder setStudent(
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          student_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public Builder mergeStudent(com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student value) {
        if (studentBuilder_ == null) {
          if (student_ != null) {
            student_ =
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.newBuilder(student_).mergeFrom(value).buildPartial();
          } else {
            student_ = value;
          }
          onChanged();
        } else {
          studentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          student_ = null;
          onChanged();
        } else {
          student_ = null;
          studentBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder getStudentBuilder() {
        
        onChanged();
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder getStudentOrBuilder() {
        if (studentBuilder_ != null) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          return student_ == null ?
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.getDefaultInstance() : student_;
        }
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder>(
                  getStudent(),
                  getParentForChildren(),
                  isClean());
          student_ = null;
        }
        return studentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tree)
    }

    // @@protoc_insertion_point(class_scope:Tree)
    private static final com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree();
    }

    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tree>
        PARSER = new com.google.protobuf.AbstractParser<Tree>() {
      @java.lang.Override
      public Tree parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Tree> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tree> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tree_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tree_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=com/ljq/demo/springboot/mybatisplus/mo" +
      "del/protobuf/Tree.proto\032@com/ljq/demo/sp" +
      "ringboot/mybatisplus/model/protobuf/Stud" +
      "ent.proto\"F\n\004Tree\022\020\n\010treeType\030\002 \001(\t\022\021\n\tp" +
      "lantDate\030\003 \001(\r\022\031\n\007student\030\004 \001(\0132\010.Studen" +
      "tB<\n0com.ljq.demo.springboot.mybatisplus" +
      ".model.entityB\006TreePbH\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.getDescriptor(),
        });
    internal_static_Tree_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Tree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tree_descriptor,
        new java.lang.String[] { "TreeType", "PlantDate", "Student", });
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
