// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ljq/demo/springboot/mybatisplus/model/protobuf/Tree.proto

package com.ljq.demo.springboot.mybatisplus.model.entity;

public final class TreePb {
  private TreePb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TreeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tree)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 树木品种
     * </pre>
     *
     * <code>string tree_type = 2;</code>
     * @return The treeType.
     */
    java.lang.String getTreeType();
    /**
     * <pre>
     * 树木品种
     * </pre>
     *
     * <code>string tree_type = 2;</code>
     * @return The bytes for treeType.
     */
    com.google.protobuf.ByteString
        getTreeTypeBytes();

    /**
     * <pre>
     * 植树时间
     * </pre>
     *
     * <code>uint32 plant_date = 3;</code>
     * @return The plantDate.
     */
    int getPlantDate();

    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     * @return Whether the student field is set.
     */
    boolean hasStudent();
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     * @return The student.
     */
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student getStudent();
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     */
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder getStudentOrBuilder();

    /**
     * <pre>
     * 学生选修课
     * </pre>
     *
     * <code>.ElectiveCourse elective_course = 5;</code>
     * @return Whether the electiveCourse field is set.
     */
    boolean hasElectiveCourse();
    /**
     * <pre>
     * 学生选修课
     * </pre>
     *
     * <code>.ElectiveCourse elective_course = 5;</code>
     * @return The electiveCourse.
     */
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse getElectiveCourse();
    /**
     * <pre>
     * 学生选修课
     * </pre>
     *
     * <code>.ElectiveCourse elective_course = 5;</code>
     */
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourseOrBuilder getElectiveCourseOrBuilder();

    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    java.util.List<com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher> 
        getTeachersList();
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher getTeachers(int index);
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    int getTeachersCount();
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    java.util.List<? extends com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder> 
        getTeachersOrBuilderList();
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder getTeachersOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 学生植树
   * </pre>
   *
   * Protobuf type {@code Tree}
   */
  public static final class Tree extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tree)
      TreeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tree.newBuilder() to construct.
    private Tree(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tree() {
      treeType_ = "";
      teachers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tree();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.class, com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.Builder.class);
    }

    public static final int TREE_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object treeType_;
    /**
     * <pre>
     * 树木品种
     * </pre>
     *
     * <code>string tree_type = 2;</code>
     * @return The treeType.
     */
    @java.lang.Override
    public java.lang.String getTreeType() {
      java.lang.Object ref = treeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        treeType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 树木品种
     * </pre>
     *
     * <code>string tree_type = 2;</code>
     * @return The bytes for treeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTreeTypeBytes() {
      java.lang.Object ref = treeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        treeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLANT_DATE_FIELD_NUMBER = 3;
    private int plantDate_;
    /**
     * <pre>
     * 植树时间
     * </pre>
     *
     * <code>uint32 plant_date = 3;</code>
     * @return The plantDate.
     */
    @java.lang.Override
    public int getPlantDate() {
      return plantDate_;
    }

    public static final int STUDENT_FIELD_NUMBER = 4;
    private com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student student_;
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     * @return Whether the student field is set.
     */
    @java.lang.Override
    public boolean hasStudent() {
      return student_ != null;
    }
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     * @return The student.
     */
    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student getStudent() {
      return student_ == null ? com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.getDefaultInstance() : student_;
    }
    /**
     * <pre>
     * 种树学生信息
     * </pre>
     *
     * <code>.Student student = 4;</code>
     */
    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder getStudentOrBuilder() {
      return getStudent();
    }

    public static final int ELECTIVE_COURSE_FIELD_NUMBER = 5;
    private com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse electiveCourse_;
    /**
     * <pre>
     * 学生选修课
     * </pre>
     *
     * <code>.ElectiveCourse elective_course = 5;</code>
     * @return Whether the electiveCourse field is set.
     */
    @java.lang.Override
    public boolean hasElectiveCourse() {
      return electiveCourse_ != null;
    }
    /**
     * <pre>
     * 学生选修课
     * </pre>
     *
     * <code>.ElectiveCourse elective_course = 5;</code>
     * @return The electiveCourse.
     */
    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse getElectiveCourse() {
      return electiveCourse_ == null ? com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.getDefaultInstance() : electiveCourse_;
    }
    /**
     * <pre>
     * 学生选修课
     * </pre>
     *
     * <code>.ElectiveCourse elective_course = 5;</code>
     */
    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourseOrBuilder getElectiveCourseOrBuilder() {
      return getElectiveCourse();
    }

    public static final int TEACHERS_FIELD_NUMBER = 6;
    private java.util.List<com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher> teachers_;
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    @java.lang.Override
    public java.util.List<com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher> getTeachersList() {
      return teachers_;
    }
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder> 
        getTeachersOrBuilderList() {
      return teachers_;
    }
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    @java.lang.Override
    public int getTeachersCount() {
      return teachers_.size();
    }
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher getTeachers(int index) {
      return teachers_.get(index);
    }
    /**
     * <pre>
     * 教师
     * </pre>
     *
     * <code>repeated .Teacher teachers = 6;</code>
     */
    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder getTeachersOrBuilder(
        int index) {
      return teachers_.get(index);
    }

    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 学生植树
     * </pre>
     *
     * Protobuf type {@code Tree}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tree)
        com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.TreeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.class, com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.Builder.class);
      }

      // Construct using com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTeachersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        treeType_ = "";

        plantDate_ = 0;

        if (studentBuilder_ == null) {
          student_ = null;
        } else {
          student_ = null;
          studentBuilder_ = null;
        }
        if (electiveCourseBuilder_ == null) {
          electiveCourse_ = null;
        } else {
          electiveCourse_ = null;
          electiveCourseBuilder_ = null;
        }
        if (teachersBuilder_ == null) {
          teachers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          teachersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.internal_static_Tree_descriptor;
      }

      @java.lang.Override
      public com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree getDefaultInstanceForType() {
        return com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree.getDefaultInstance();
      }

      @java.lang.Override
      public com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree build() {
        com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree buildPartial() {
        com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree result = new com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree(this);
        int from_bitField0_ = bitField0_;
        result.treeType_ = treeType_;
        result.plantDate_ = plantDate_;
        if (studentBuilder_ == null) {
          result.student_ = student_;
        } else {
          result.student_ = studentBuilder_.build();
        }
        if (electiveCourseBuilder_ == null) {
          result.electiveCourse_ = electiveCourse_;
        } else {
          result.electiveCourse_ = electiveCourseBuilder_.build();
        }
        if (teachersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            teachers_ = java.util.Collections.unmodifiableList(teachers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.teachers_ = teachers_;
        } else {
          result.teachers_ = teachersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private java.lang.Object treeType_ = "";
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string tree_type = 2;</code>
       * @return The treeType.
       */
      public java.lang.String getTreeType() {
        java.lang.Object ref = treeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          treeType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string tree_type = 2;</code>
       * @return The bytes for treeType.
       */
      public com.google.protobuf.ByteString
          getTreeTypeBytes() {
        java.lang.Object ref = treeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          treeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string tree_type = 2;</code>
       * @param value The treeType to set.
       * @return This builder for chaining.
       */
      public Builder setTreeType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        treeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string tree_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTreeType() {
        
        treeType_ = getDefaultInstance().getTreeType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 树木品种
       * </pre>
       *
       * <code>string tree_type = 2;</code>
       * @param value The bytes for treeType to set.
       * @return This builder for chaining.
       */
      public Builder setTreeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        treeType_ = value;
        onChanged();
        return this;
      }

      private int plantDate_ ;
      /**
       * <pre>
       * 植树时间
       * </pre>
       *
       * <code>uint32 plant_date = 3;</code>
       * @return The plantDate.
       */
      @java.lang.Override
      public int getPlantDate() {
        return plantDate_;
      }
      /**
       * <pre>
       * 植树时间
       * </pre>
       *
       * <code>uint32 plant_date = 3;</code>
       * @param value The plantDate to set.
       * @return This builder for chaining.
       */
      public Builder setPlantDate(int value) {
        
        plantDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 植树时间
       * </pre>
       *
       * <code>uint32 plant_date = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlantDate() {
        
        plantDate_ = 0;
        onChanged();
        return this;
      }

      private com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student student_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder> studentBuilder_;
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       * @return Whether the student field is set.
       */
      public boolean hasStudent() {
        return studentBuilder_ != null || student_ != null;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       * @return The student.
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student getStudent() {
        if (studentBuilder_ == null) {
          return student_ == null ? com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.getDefaultInstance() : student_;
        } else {
          return studentBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public Builder setStudent(com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          student_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public Builder setStudent(
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          student_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public Builder mergeStudent(com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student value) {
        if (studentBuilder_ == null) {
          if (student_ != null) {
            student_ =
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.newBuilder(student_).mergeFrom(value).buildPartial();
          } else {
            student_ = value;
          }
          onChanged();
        } else {
          studentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          student_ = null;
          onChanged();
        } else {
          student_ = null;
          studentBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder getStudentBuilder() {
        
        onChanged();
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder getStudentOrBuilder() {
        if (studentBuilder_ != null) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          return student_ == null ?
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.getDefaultInstance() : student_;
        }
      }
      /**
       * <pre>
       * 种树学生信息
       * </pre>
       *
       * <code>.Student student = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Student.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.StudentOrBuilder>(
                  getStudent(),
                  getParentForChildren(),
                  isClean());
          student_ = null;
        }
        return studentBuilder_;
      }

      private com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse electiveCourse_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourseOrBuilder> electiveCourseBuilder_;
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       * @return Whether the electiveCourse field is set.
       */
      public boolean hasElectiveCourse() {
        return electiveCourseBuilder_ != null || electiveCourse_ != null;
      }
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       * @return The electiveCourse.
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse getElectiveCourse() {
        if (electiveCourseBuilder_ == null) {
          return electiveCourse_ == null ? com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.getDefaultInstance() : electiveCourse_;
        } else {
          return electiveCourseBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       */
      public Builder setElectiveCourse(com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse value) {
        if (electiveCourseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          electiveCourse_ = value;
          onChanged();
        } else {
          electiveCourseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       */
      public Builder setElectiveCourse(
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.Builder builderForValue) {
        if (electiveCourseBuilder_ == null) {
          electiveCourse_ = builderForValue.build();
          onChanged();
        } else {
          electiveCourseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       */
      public Builder mergeElectiveCourse(com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse value) {
        if (electiveCourseBuilder_ == null) {
          if (electiveCourse_ != null) {
            electiveCourse_ =
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.newBuilder(electiveCourse_).mergeFrom(value).buildPartial();
          } else {
            electiveCourse_ = value;
          }
          onChanged();
        } else {
          electiveCourseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       */
      public Builder clearElectiveCourse() {
        if (electiveCourseBuilder_ == null) {
          electiveCourse_ = null;
          onChanged();
        } else {
          electiveCourse_ = null;
          electiveCourseBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.Builder getElectiveCourseBuilder() {
        
        onChanged();
        return getElectiveCourseFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourseOrBuilder getElectiveCourseOrBuilder() {
        if (electiveCourseBuilder_ != null) {
          return electiveCourseBuilder_.getMessageOrBuilder();
        } else {
          return electiveCourse_ == null ?
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.getDefaultInstance() : electiveCourse_;
        }
      }
      /**
       * <pre>
       * 学生选修课
       * </pre>
       *
       * <code>.ElectiveCourse elective_course = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourseOrBuilder> 
          getElectiveCourseFieldBuilder() {
        if (electiveCourseBuilder_ == null) {
          electiveCourseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourse.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.ElectiveCourseOrBuilder>(
                  getElectiveCourse(),
                  getParentForChildren(),
                  isClean());
          electiveCourse_ = null;
        }
        return electiveCourseBuilder_;
      }

      private java.util.List<com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher> teachers_ =
        java.util.Collections.emptyList();
      private void ensureTeachersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          teachers_ = new java.util.ArrayList<com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher>(teachers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder> teachersBuilder_;

      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public java.util.List<com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher> getTeachersList() {
        if (teachersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(teachers_);
        } else {
          return teachersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public int getTeachersCount() {
        if (teachersBuilder_ == null) {
          return teachers_.size();
        } else {
          return teachersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher getTeachers(int index) {
        if (teachersBuilder_ == null) {
          return teachers_.get(index);
        } else {
          return teachersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder setTeachers(
          int index, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.set(index, value);
          onChanged();
        } else {
          teachersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder setTeachers(
          int index, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.set(index, builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder addTeachers(com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.add(value);
          onChanged();
        } else {
          teachersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder addTeachers(
          int index, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.add(index, value);
          onChanged();
        } else {
          teachersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder addTeachers(
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.add(builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder addTeachers(
          int index, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.add(index, builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder addAllTeachers(
          java.lang.Iterable<? extends com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher> values) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, teachers_);
          onChanged();
        } else {
          teachersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder clearTeachers() {
        if (teachersBuilder_ == null) {
          teachers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          teachersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public Builder removeTeachers(int index) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.remove(index);
          onChanged();
        } else {
          teachersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder getTeachersBuilder(
          int index) {
        return getTeachersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder getTeachersOrBuilder(
          int index) {
        if (teachersBuilder_ == null) {
          return teachers_.get(index);  } else {
          return teachersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public java.util.List<? extends com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder> 
           getTeachersOrBuilderList() {
        if (teachersBuilder_ != null) {
          return teachersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(teachers_);
        }
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder addTeachersBuilder() {
        return getTeachersFieldBuilder().addBuilder(
            com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.getDefaultInstance());
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder addTeachersBuilder(
          int index) {
        return getTeachersFieldBuilder().addBuilder(
            index, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.getDefaultInstance());
      }
      /**
       * <pre>
       * 教师
       * </pre>
       *
       * <code>repeated .Teacher teachers = 6;</code>
       */
      public java.util.List<com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder> 
           getTeachersBuilderList() {
        return getTeachersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder> 
          getTeachersFieldBuilder() {
        if (teachersBuilder_ == null) {
          teachersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.Teacher.Builder, com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.TeacherOrBuilder>(
                  teachers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          teachers_ = null;
        }
        return teachersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tree)
    }

    // @@protoc_insertion_point(class_scope:Tree)
    private static final com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree();
    }

    public static com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tree>
        PARSER = new com.google.protobuf.AbstractParser<Tree>() {
      @java.lang.Override
      public Tree parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Tree> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tree> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ljq.demo.springboot.mybatisplus.model.entity.TreePb.Tree getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tree_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tree_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=com/ljq/demo/springboot/mybatisplus/mo" +
      "del/protobuf/Tree.proto\032@com/ljq/demo/sp" +
      "ringboot/mybatisplus/model/protobuf/Stud" +
      "ent.proto\"\216\001\n\004Tree\022\021\n\ttree_type\030\002 \001(\t\022\022\n" +
      "\nplant_date\030\003 \001(\r\022\031\n\007student\030\004 \001(\0132\010.Stu" +
      "dent\022(\n\017elective_course\030\005 \001(\0132\017.Elective" +
      "Course\022\032\n\010teachers\030\006 \003(\0132\010.TeacherB<\n0co" +
      "m.ljq.demo.springboot.mybatisplus.model." +
      "entityB\006TreePbH\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.getDescriptor(),
        });
    internal_static_Tree_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Tree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tree_descriptor,
        new java.lang.String[] { "TreeType", "PlantDate", "Student", "ElectiveCourse", "Teachers", });
    com.ljq.demo.springboot.mybatisplus.model.entity.StudentPb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
