## config

## server
server:
  port: 8850

## spring
spring:
  application:
    name: demo-read-write
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      jdbc-url: "jdbc:mysql://172.16.140.10:3306/demo?useUnicode=true&characterEncoding=utf8\
        &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
        &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true\
        &nullCatalogMeansCurrent=true"
      username: root
      password: "Qwert12345!"
    slave:
      jdbc-url: "jdbc:mysql://172.16.140.11:3306/demo?useUnicode=true&characterEncoding=utf8\
        &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
        &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true\
        &nullCatalogMeansCurrent=true"
      username: read_user
      password: "12345!Qwert"

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.ljq.demo.springboot.readwrite.model.entity
