## config

## server
server:
  port: 8680

## spring config
spring:
  datasource:
    url: "jdbc:mysql://172.16.140.10:3306/demo?useUnicode=true&characterEncoding=utf8\
      &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
      &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true"
    username: root
    password: "Qwert12345!"
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.ljq.demo.springboot.*.model.entity

## Swagger3
swagger3:
  enable: true
  title: Swagger3 demo
  description: Swagger3 demo api document
  authHeaderKey: token







