## environment-test

## tomcat server
server:
  port: 8000

spring:
  ## datasource
  datasource:
    url: "jdbc:mysql://192.168.6.109:13306/demo?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true\
      &useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=true&allowMultiQueries=true&autoReconnect=true"
    username: root
    password: sasa
  # redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 7749
    password: demo@apq
    timeout: 10000ms
    jedis:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 50
        max-wait: 100s
  # rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmqadmin
    password: rootpass100

# yml demo
person:
  name: Tom
  age: 40
  parent:
    mother:
      name: Lily
      age: 65
    father:
      name: Bob
      age: 68

# Swagger config
swagger:
  enable: true

## aliyun oss
## 配置说明参考: com.ljq.demo.springboot.common.config.OSSConfig.class
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  url: https://xxxx.oss-cn-hangzhou.aliyuncs.com/
  accessKeyId: your_accessKey_id
  accessKeySecret: your_accessKey_secret
  bucketName: your_bucket_name

## sftp 附件上传配置
uploadSftp:
  host: 172.16.140.10
  port: 22
  username: root
  password: root
  path: /home/ljq/upload

## Redisson 分布式锁配置
redisson:
  address: redis://172.16.140.10:7749
  database: 9
  password: 21cde022-a5da-626e-c8f4-04c99ed3a181
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  connectionTimeout: 10000
  timeout: 3000
