## config

## server
server:
  port: 8450

## spring config
spring:
  datasource:
    url: "jdbc:mysql://120.78.93.174:3306/appserver_iot_test?useUnicode=true&characterEncoding=utf8\
      &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
      &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true\
      &nullCatalogMeansCurrent=true"
    username: root
    password: "123456"
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.ljq.dmeo.springboot.mybatisplus.model.entity

## log
logging:
  level:
    com.ljq.demo.springboot.mybatisplus.dao: debug
    com.ljq.demo.springboot.mybatisplus: debug

